build:
    runs-on: ubuntu-latest
    # Pas besoin de working-directory ici car on est à la racine du projet.
    steps:
      - name: 📥 Checkout du code
        uses: actions/checkout@v4

      - name: 🚀 Installer PNPM
        run: npm install -g pnpm

      - name: ⚙️ Setup de l'environnement Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: 📦 Installation des dépendances
        run: pnpm install

      - name: 🏗️ Build du projet
        run: pnpm run build

      - name: 🚫 Désactiver Jekyll
        run: touch dist/.nojekyll

      - name: 📤 Création du GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist
